############################################
# Tokyo SSM Automation for Incident Response
############################################

resource "aws_ssm_document" "tokyo_alarm_report_runbook" {
  name            = "${var.project_name}-tokyo-incident-report"
  document_type   = "Automation"
  document_format = "JSON"

  tags = merge(var.common_tags, {
    Name        = "${var.project_name}-tokyo-incident-report"
    Purpose     = "Incident response automation"
    Environment = "production"
    Region      = "Tokyo"
  })

  content = jsonencode({
    schemaVersion = "0.3"
    description   = "Tokyo alarm report automation runbook with translation integration (receives S3 report keys)."
    parameters = {
      IncidentId = {
        type        = "String"
        description = "Incident identifier"
      }
      AlarmName = {
        type        = "String"
        description = "CloudWatch alarm name"
      }
      ReportBucket = {
        type        = "String"
        description = "S3 bucket with report bundle"
      }
      ReportJsonKey = {
        type        = "String"
        description = "S3 key for JSON evidence bundle"
      }
      ReportMarkdownKey = {
        type        = "String"
        description = "S3 key for Markdown report"
      }
      AsgName = {
        type        = "String"
        description = "Auto Scaling Group name to refresh (optional)"
        default     = ""
      }
      TranslationBucket = {
        type        = "String"
        description = "S3 bucket for translation input"
      }
      ReportTemplate = {
        type        = "String"
        description = "Incident report template (Multi-language)"
        default     = <<-TPL
# Incident Report: {{incident_id}} -- {{title}}
# インシデントレポート: {{incident_id}} -- {{title}}

## 1. Executive Summary / エグゼクティブサマリー
- Impact / 影響:
- Customer/User Symptoms / 顧客・ユーザーの症状:
- Detection Method (alarm/logs) / 検出方法 (アラーム・ログ):
- Severity / 重要度:
- Start Time (UTC) / 開始時間 (UTC):
- End Time (UTC) / 終了時間 (UTC):
- Duration / 持続時間:

## 2. Timeline (UTC) / タイムライン (UTC)
| Time | Signal | Evidence |
|------|--------|----------|
|      | Alarm triggered / アラーム発生 | |
|      | First error seen / 最初のエラー確認 | |
|      | Triage started / トリアージ開始 | |
|      | Root cause identified / 根本原因特定 | |
|      | Fix applied / 修正適用 | |
|      | Service restored / サービス復旧 | |
|      | Alarm cleared / アラーム解除 | |

## 3. Scope and Blast Radius / 範囲・影響範囲
- Affected components / 影響を受けたコンポーネント:
- Entry point (ALB / WAF) / エントリーポイント (ALB / WAF):
- Downstream dependency (RDS) / 下流依存関係 (RDS):
- Regions/AZs / リージョン・AZ:

## 4. Evidence Collected / 収集した証拠
### 4.1 CloudWatch Alarm
- Alarm name / アラーム名:
- Metric / メトリック:
- Threshold / 閾値:
- State changes / 状態変化:

### 4.2 App Logs (CloudWatch Logs Insights)
- Error rate over time (1m bins) / 時系列エラー率 (1分間隔):
- Top error signatures (top 5) / 主要エラーパターン (上位5):
- Most recent error lines (top 10) / 最新エラー行 (上位10):

### 4.3 WAF Logs (CloudWatch Logs Insights)
- Allow vs Block / 許可 vs ブロック:
- Top client IPs / 上位クライアントIP:
- Top URIs / 上位URI:
- Top terminating rules / 上位終端ルール:

### 4.4 Configuration Sources (for Recovery) / 設定ソース (復旧用)
- Parameter Store: /lab/db/* (endpoint/port/name)
- Secrets Manager: {{secret_name}} (host/port/dbname/username/password)
- Notes on drift / ドリフトに関する注記:

## 5. Root Cause Analysis / 根本原因分析
- Root cause category / 根本原因カテゴリ: (Cred drift | Network isolation | DB interruption | External attack | Other)
- Exact failure mechanism / 正確な失敗メカニズム:
- Why it wasn't prevented / なぜ防止できなかったか:
- Contributing factors / 要因:

## 6. Resolution / 解決方法
- Actions taken / 実行したアクション:
- Validation checks / 検証チェック:
- Evidence of recovery / 復旧証拠 (curl + alarm OK + logs stabilized):

## 7. Preventive Actions / 予防策
- Immediate (today) / 即座 (今日):
- Short-term (1-2 weeks) / 短期 (1-2週間):
- Long-term (1-2 months) / 長期 (1-2ヶ月):

## 8. Appendix / 付録
- Key CLI commands used / 使用した主要CLIコマンド:
- Logs Insights queries used / 使用したログインサイトクエリ:  
- Report generated by / レポート生成元: Amazon Bedrock model {{model_id}}
- Translation Status / 翻訳ステータス: {{translation_status}}
TPL
      }
    }
    mainSteps = [
      {
        name   = "LogInputs"
        action = "aws:executeScript"
        inputs = {
          Runtime = "python3.11"
          Handler = "handler"
          InputPayload = {
            IncidentId        = "{{ IncidentId }}"
            AlarmName         = "{{ AlarmName }}"
            ReportBucket      = "{{ ReportBucket }}"
            ReportJsonKey     = "{{ ReportJsonKey }}"
            ReportMarkdownKey = "{{ ReportMarkdownKey }}"
            AsgName           = "{{ AsgName }}"
            TranslationBucket = "{{ TranslationBucket }}"
          }
          Script = <<-PY
def handler(event, context):
    return {
        "message": "Received alarm report bundle for Tokyo processing",
        "report": {
            "bucket": event.get("ReportBucket"),
            "json_key": event.get("ReportJsonKey"),
            "markdown_key": event.get("ReportMarkdownKey"),
        },
        "automation": {
            "asg_name": event.get("AsgName"),
        },
        "translation": {
            "bucket": event.get("TranslationBucket"),
            "source_language": "en",
            "target_language": "ja"
        },
        "region": "ap-northeast-1",
        "event": event,
    }
PY
        }
        outputs = [
          {
            Name     = "ReportBundle"
            Selector = "$.report"
            Type     = "StringMap"
          },
          {
            Name     = "AsgName"
            Selector = "$.automation.asg_name"
            Type     = "String"
          },
          {
            Name     = "TranslationInfo"
            Selector = "$.translation"
            Type     = "StringMap"
          }
        ]
      }
      ,
      {
        name   = "TriggerTranslation"
        action = "aws:executeScript"
        inputs = {
          Runtime = "python3.11"
          Handler = "handler"
          InputPayload = {
            ReportBucket      = "{{ ReportBucket }}"
            ReportMarkdownKey = "{{ ReportMarkdownKey }}"
            TranslationBucket = "{{ TranslationBucket }}"
            IncidentId        = "{{ IncidentId }}"
          }
          Script = <<-PY
import boto3
import json
from datetime import datetime

def handler(event, context):
    s3 = boto3.client('s3')
    
    try:
        # Copy report to translation input bucket
        report_bucket = event.get("ReportBucket")
        report_key = event.get("ReportMarkdownKey")
        translation_bucket = event.get("TranslationBucket")
        incident_id = event.get("IncidentId")
        
        # Create translation input key with timestamp
        timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
        translation_key = f"incident-reports/en/ir-{incident_id}-{timestamp}.md"
        
        # Copy source object
        copy_source = {
            'Bucket': report_bucket,
            'Key': report_key
        }
        
        s3.copy_object(
            CopySource=copy_source,
            Bucket=translation_bucket,
            Key=translation_key,
            Metadata={
                'source-language': 'en',
                'target-language': 'ja',
                'incident-id': incident_id,
                'translation-trigger': 'ssm-automation'
            },
            MetadataDirective='REPLACE'
        )
        
        return {
            "status": "success",
            "message": f"Report copied to translation bucket for Japanese translation",
            "translation_input": {
                "bucket": translation_bucket,
                "key": translation_key,
                "source_lang": "en",
                "target_lang": "ja"
            }
        }
    
    except Exception as e:
        return {
            "status": "error", 
            "message": f"Translation trigger failed: {str(e)}"
        }
PY
        }
        outputs = [
          {
            Name     = "TranslationResult"
            Selector = "$.translation_input"
            Type     = "StringMap"
          }
        ]
      }
      ,
      {
        name   = "BranchOnAsgName"
        action = "aws:branch"
        inputs = {
          Choices = [
            {
              NextStep     = "Noop"
              Variable     = "{{ AsgName }}"
              StringEquals = ""
            }
          ]
          Default = "DescribeAsg"
        }
      }
      ,
      {
        name   = "DescribeAsg"
        action = "aws:executeAwsApi"
        inputs = {
          Service = "autoscaling"
          Api     = "DescribeAutoScalingGroups"
          AutoScalingGroupNames = [
            "{{ AsgName }}"
          ]
        }
      }
      ,
      {
        name   = "StartInstanceRefresh"
        action = "aws:executeAwsApi"
        inputs = {
          Service              = "autoscaling"
          Api                  = "StartInstanceRefresh"
          AutoScalingGroupName = "{{ AsgName }}"
          Preferences = {
            MinHealthyPercentage = 90
            InstanceWarmup       = 300
          }
        }
      }
      ,
      {
        name   = "Noop"
        action = "aws:executeScript"
        inputs = {
          Runtime = "python3.11"
          Handler = "handler"
          Script  = "def handler(event, context):\\n    return {'message': 'No ASG refresh requested - Tokyo automation complete'}\\n"
        }
      }
    ]
    outputs = [
      "LogInputs.ReportBundle",
      "LogInputs.TranslationInfo",
      "TriggerTranslation.TranslationResult"
    ]
  })
}

# IAM role for SSM automation execution
resource "aws_iam_role" "tokyo_ssm_automation_role" {
  name = "${var.project_name}-tokyo-ssm-automation-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "ssm.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })

  tags = merge(var.common_tags, {
    Name        = "${var.project_name}-tokyo-ssm-automation-role"
    Purpose     = "SSM automation execution"
    Environment = "production"
    Region      = "Tokyo"
  })
}

# IAM policy for SSM automation
resource "aws_iam_policy" "tokyo_ssm_automation_policy" {
  name = "${var.project_name}-tokyo-ssm-automation-policy"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "autoscaling:DescribeAutoScalingGroups",
          "autoscaling:StartInstanceRefresh"
        ]
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:PutObject",
          "s3:ListBucket"
        ]
        Resource = [
          aws_s3_bucket.tokyo_ir_reports_bucket.arn,
          "${aws_s3_bucket.tokyo_ir_reports_bucket.arn}/*",
          module.tokyo_translation.input_bucket_arn,
          "${module.tokyo_translation.input_bucket_arn}/*"
        ]
      },
      {
        Effect = "Allow"
        Action = [
          "kms:Decrypt",
          "kms:DescribeKey"
        ]
        Resource = aws_kms_key.taaops_kms_key01.arn
      }
    ]
  })

  tags = merge(var.common_tags, {
    Name        = "${var.project_name}-tokyo-ssm-automation-policy"
    Purpose     = "SSM automation permissions"
    Environment = "production"
    Region      = "Tokyo"
  })
}

resource "aws_iam_role_policy_attachment" "tokyo_ssm_automation_attach" {
  role       = aws_iam_role.tokyo_ssm_automation_role.name
  policy_arn = aws_iam_policy.tokyo_ssm_automation_policy.arn
}

# Attach the SSM service role policy
resource "aws_iam_role_policy_attachment" "tokyo_ssm_automation_service_role" {
  role       = aws_iam_role.tokyo_ssm_automation_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole"
}