resource "aws_ssm_document" "alarm_report_runbook" {
  name            = "${var.project_name}-incident-report"
  document_type   = "Automation"
  document_format = "JSON"

  content = jsonencode({
    schemaVersion = "0.3"
    description   = "Alarm report automation runbook (receives S3 report keys)."
    parameters = {
      IncidentId = {
        type        = "String"
        description = "Incident identifier"
      }
      AlarmName = {
        type        = "String"
        description = "CloudWatch alarm name"
      }
      ReportBucket = {
        type        = "String"
        description = "S3 bucket with report bundle"
      }
      ReportJsonKey = {
        type        = "String"
        description = "S3 key for JSON evidence bundle"
      }
      ReportMarkdownKey = {
        type        = "String"
        description = "S3 key for Markdown report"
      }
      AsgName = {
        type        = "String"
        description = "Auto Scaling Group name to refresh (optional)"
        default     = ""
      }
      ReportTemplate = {
        type        = "String"
        description = "Incident report template"
        default     = <<-TPL
# Incident Report: {{incident_id}} -- {{title}}

## 1. Executive Summary
- Impact:
- Customer/User Symptoms:
- Detection Method (alarm/logs):
- Severity:
- Start Time (UTC):
- End Time (UTC):
- Duration:

## 2. Timeline (UTC)
| Time | Signal | Evidence |
|------|--------|----------|
|      | Alarm triggered | |
|      | First error seen | |
|      | Triage started | |
|      | Root cause identified | |
|      | Fix applied | |
|      | Service restored | |
|      | Alarm cleared | |

## 3. Scope and Blast Radius
- Affected components:
- Entry point (ALB / WAF):
- Downstream dependency (RDS):
- Regions/AZs:

## 4. Evidence Collected
### 4.1 CloudWatch Alarm
- Alarm name:
- Metric:
- Threshold:
- State changes:

### 4.2 App Logs (CloudWatch Logs Insights)
- Error rate over time (1m bins):
- Top error signatures (top 5):
- Most recent error lines (top 10):

### 4.3 WAF Logs (CloudWatch Logs Insights)
- Allow vs Block:
- Top client IPs:
- Top URIs:
- Top terminating rules:

### 4.4 Configuration Sources (for Recovery)
- Parameter Store: /lab/db/* (endpoint/port/name)
- Secrets Manager: {{secret_name}} (host/port/dbname/username/password)
- Notes on drift:

## 5. Root Cause Analysis
- Root cause category: (Cred drift | Network isolation | DB interruption | External attack | Other)
- Exact failure mechanism:
- Why it wasn't prevented:
- Contributing factors:

## 6. Resolution
- Actions taken:
- Validation checks:
- Evidence of recovery (curl + alarm OK + logs stabilized):

## 7. Preventive Actions
- Immediate (today):
- Short-term (1-2 weeks):
- Long-term (1-2 months):

## 8. Appendix
- Key CLI commands used:
- Logs Insights queries used:
- Report generated by: Amazon Bedrock model {{model_id}}
TPL
      }
    }
    mainSteps = [
      {
        name   = "LogInputs"
        action = "aws:executeScript"
        inputs = {
          Runtime = "python3.11"
          Handler = "handler"
          InputPayload = {
            IncidentId        = "{{ IncidentId }}"
            AlarmName         = "{{ AlarmName }}"
            ReportBucket      = "{{ ReportBucket }}"
            ReportJsonKey     = "{{ ReportJsonKey }}"
            ReportMarkdownKey = "{{ ReportMarkdownKey }}"
            AsgName           = "{{ AsgName }}"
          }
          Script = <<-PY
def handler(event, context):
    return {
        "message": "Received alarm report bundle",
        "report": {
            "bucket": event.get("ReportBucket"),
            "json_key": event.get("ReportJsonKey"),
            "markdown_key": event.get("ReportMarkdownKey"),
        },
        "automation": {
            "asg_name": event.get("AsgName"),
        },
        "event": event,
    }
PY
        }
        outputs = [
          {
            Name     = "ReportBundle"
            Selector = "$.report"
            Type     = "StringMap"
          },
          {
            Name     = "AsgName"
            Selector = "$.automation.asg_name"
            Type     = "String"
          }
        ]
      }
      ,
      {
        name   = "BranchOnAsgName"
        action = "aws:branch"
        inputs = {
          Choices = [
            {
              NextStep     = "Noop"
              Variable     = "{{ AsgName }}"
              StringEquals = ""
            }
          ]
          Default = "DescribeAsg"
        }
      }
      ,
      {
        name   = "DescribeAsg"
        action = "aws:executeAwsApi"
        inputs = {
          Service = "autoscaling"
          Api     = "DescribeAutoScalingGroups"
          AutoScalingGroupNames = [
            "{{ AsgName }}"
          ]
        }
      }
      ,
      {
        name   = "StartInstanceRefresh"
        action = "aws:executeAwsApi"
        inputs = {
          Service              = "autoscaling"
          Api                  = "StartInstanceRefresh"
          AutoScalingGroupName = "{{ AsgName }}"
          Preferences = {
            MinHealthyPercentage = 90
            InstanceWarmup       = 300
          }
        }
      }
      ,
      {
        name   = "Noop"
        action = "aws:executeScript"
        inputs = {
          Runtime = "python3.11"
          Handler = "handler"
          Script  = "def handler(event, context):\\n    return {'message': 'No ASG refresh requested'}\\n"
        }
      }
    ]
    outputs = [
      "LogInputs.ReportBundle"
    ]
  })
}
